/**
 * Speed Limit Sign -- Vibe3D entry point.
 *
 * Generated by thaikit's scripts/build-vibe3d-registry.mjs. Once installed this
 * file is yours: editing it is the point of a source-first registry.
 *
 * The model itself is in ./createObjectModel, unmodified.
 */
import {
  Color,
  Group,
  Object3D,
  PerspectiveCamera,
  Scene,
} from 'three';
import type { Material, Mesh, Texture } from 'three';

import {
  createModel as createBaseModel,
  createSpeedLimitSignLookDevLights,
  frameSpeedLimitSignCamera,
  type ProceduralModelOptions,
} from './createObjectModel';

export type { ProceduralModelOptions } from './createObjectModel';

/**
 * The prop's own one-argument factory, re-exported under vibe3d's name.
 *
 * thaikit's factories export BOTH `createObjectModel(spec, options)` -- its
 * historical shape, kept for the render harness and the level editor -- and
 * `createModel(options)`, which is what this wraps. So this file no longer
 * knows the two-argument form exists, and the only thing it adds is the
 * baseUrl default below.
 */

export function createModel(options: ProceduralModelOptions = {}): Group {
  return createBaseModel(options);
}

/** The shape Vibe3D's docs catalogue expects back from `createPreview`. */
export interface ModelPreview {
  scene: Scene;
  root: Group;
  camera: PerspectiveCamera;
  update(deltaSeconds: number): void;
  dispose(): void;
}

export interface PreviewOptions extends ProceduralModelOptions {
  /** Viewport aspect ratio. */
  aspect?: number;
  /** Seconds into the turntable, so a captured frame is reproducible. */
  time?: number;
  /** Turntable speed. Zero holds the opening three-quarter view. */
  degreesPerSecond?: number;
  elevationDeg?: number;
  margin?: number;
}

/**
 * A preview scene for the docs gallery. Everything it adds is preview-only and
 * never reaches the installed model root.
 *
 * The turntable moves the CAMERA rather than the prop: these props are pivoted
 * base-center, not bounding-box-center, so spinning the root would swing it
 * around an off-centre axis and wobble in frame.
 */
export function createPreview(options: PreviewOptions = {}): ModelPreview {
  const {
    aspect = 16 / 9,
    time = 0,
    degreesPerSecond = 18,
    elevationDeg = 20,
    margin = 1.25,
    ...modelOptions
  } = options;

  const root = createModel(modelOptions);

  const scene = new Scene();
  // The backdrop the model's own look-dev targets were authored against, so the
  // gallery tile matches the render the review looked at.
  const lookDev = root.userData.lookDevTargets as { backgroundColor?: string } | undefined;
  scene.background = new Color(lookDev?.backgroundColor ?? '#3A3A3A');
  scene.add(root);

  const lights = createSpeedLimitSignLookDevLights('neutral');
  lights.userData.excludeFromExport = true;
  scene.add(lights);

  const camera = new PerspectiveCamera(35, aspect, 0.01, 1000);
  let elapsed = time;
  const aim = () => {
    frameSpeedLimitSignCamera(camera, root, {
      margin,
      elevationDeg,
      azimuthDeg: 35 + elapsed * degreesPerSecond,
    });
  };
  aim();

  let disposed = false;

  return {
    scene,
    root,
    camera,
    update(deltaSeconds: number): void {
      if (disposed || degreesPerSecond === 0) return;
      elapsed += deltaSeconds;
      aim();
    },
    dispose(): void {
      if (disposed) return;            // idempotent, per the vibe-model contract
      disposed = true;
      const geometries = new Set<{ dispose(): void }>();
      const materials = new Set<Material>();
      scene.traverse((node: Object3D) => {
        const mesh = node as Mesh;
        if (!mesh.isMesh) return;
        geometries.add(mesh.geometry);
        for (const material of Array.isArray(mesh.material) ? mesh.material : [mesh.material]) {
          if (material) materials.add(material);
        }
      });
      for (const geometry of geometries) geometry.dispose();
      for (const material of materials) {
        // Textures are synthesised per material, so nothing else holds them.
        for (const value of Object.values(material as unknown as Record<string, unknown>)) {
          const texture = value as Texture | null;
          if (texture && (texture as { isTexture?: boolean }).isTexture) texture.dispose();
        }
        material.dispose();
      }
      scene.clear();
    },
  };
}

export default createModel;
