/**
 * Turn one vibe3d model item into a thaikit-shaped module.
 *
 * thaikit's whole host contract is `createObjectModel(spec, options) -> Group`
 * on a CommonJS bundle with `three` external. A vibe3d item exports
 * `createModel(...)` returning either a Group (thaikit's own export) or a
 * ModelInstance `{ root, update, dispose, ... }` (scifi-kit, medieval-kit).
 * The wrapper normalises both and the existing esbuild step does the rest.
 */
import path from 'node:path';

import { buildModule } from '../bundle.mjs';

/** The file a vibe3d installer would import for this item. */
export function pickEntry(item) {
  const files = (item.files ?? []).filter((f) => /\.(ts|tsx|js|mjs)$/.test(f.target) && !/\.test\.[tj]s$/.test(f.target));
  const under = files.filter((f) => f.target.startsWith('{models}/'));
  const by = (re) => under.find((f) => re.test(f.target));
  const chosen =
    by(/\/model\.tsx?$/) ?? by(/\/index\.tsx?$/) ?? (under.length === 1 ? under[0] : null) ?? under[0] ?? files[0] ?? null;
  const strategy = !chosen ? 'none' : /\/model\.tsx?$/.test(chosen.target) ? 'model.ts' : /\/index\.tsx?$/.test(chosen.target) ? 'index.ts' : under.length === 1 ? 'single' : 'first';
  return { entry: chosen?.target ?? null, strategy };
}

export function wrapperSource(entryAbs) {
  const spec = entryAbs.split(path.sep).join('/');
  return `// Generated by thaikit's pack installer. Adapts a vibe3d item to createObjectModel(spec, options).
import * as m from ${JSON.stringify(spec)};

function pickFactory(mod: any): ((...args: any[]) => any) | null {
  if (typeof mod.createModel === 'function') return mod.createModel;
  if (typeof mod.default === 'function') return mod.default;
  for (const [k, v] of Object.entries(mod)) if (typeof v === 'function' && /^create/.test(k) && !/Preview$/.test(k)) return v as any;
  return null;
}

export function createObjectModel(_spec: unknown, options: any = {}) {
  const fn = pickFactory(m);
  if (!fn) throw new Error('no factory export (createModel / default / create*)');
  let out: any = fn(options ?? {});
  if (out && !out.isObject3D && out.root && out.root.isObject3D) {
    const inst = out;
    out = inst.root;
    out.userData.vibe3dInstance = {
      update: typeof inst.update === 'function' ? inst.update.bind(inst) : null,
      dispose: typeof inst.dispose === 'function' ? inst.dispose.bind(inst) : null,
      configure: typeof inst.configure === 'function' ? inst.configure.bind(inst) : null,
      parts: inst.parts ? Object.keys(inst.parts) : [],
      sockets: inst.sockets ? Object.keys(inst.sockets) : [],
    };
  }
  if (!out || !out.isObject3D) throw new Error('factory did not return an Object3D or { root }');
  return out;
}

export default createObjectModel;
`;
}

export const PACK_EXTERNALS = ['three', 'three/webgpu', 'three/tsl'];

export async function bundleItem({ entryAbs, wrapperFile, outFile, srcDir }) {
  const alias = {
    '@vibe3d': path.join(srcDir, 'vibe3d'),
    '@/vibe3d': path.join(srcDir, 'vibe3d'),
    '@/models': path.join(srcDir, 'models'),
    '@/lib/vibe3d': path.join(srcDir, 'vibe3d'),
    '~/vibe3d': path.join(srcDir, 'vibe3d'),
    '~/models': path.join(srcDir, 'models'),
  };
  void entryAbs;
  return buildModule({ entry: wrapperFile, outFile, external: PACK_EXTERNALS, alias, sourcemap: false });
}
