/** Authoring dimensions, not botanical maximum sizes. Seeds are part of the asset contract. */
const rows = [
 ['bougainvillea','Bougainvillea','Bougainvillea glabra','shrub',1.25,1.5,'arching woody stems with glossy ovate leaves and sparse magenta bracts','a slender leafy sprig with ovate green leaves and a few magenta papery bracts',true],
 ['ixora','Ixora','Ixora coccinea','shrub',1,.8,'dense rounded shrub with opposite glossy leaves and small orange-red flower clusters','a short leafy sprig with opposite glossy oval leaves and one small orange-red flower cluster',false],
 ['croton','Croton','Codiaeum variegatum','broadleaf',.8,1,'upright clusters of leathery variegated green gold and burgundy leaves','one leathery lance-shaped croton leaf with green gold and burgundy veins',true],
 ['snake-plant','Snake Plant','Dracaena trifasciata','upright',.45,.7,'cluster of stiff upright sword leaves with dark green cross-banding and narrow yellow edges','one long upright sword-shaped snake-plant leaf with green cross-banding and narrow yellow edges',true],
 ['birds-nest-fern','Bird’s-nest Fern','Asplenium nidus','rosette',1,.6,'lush radial rosette of glossy bright green strap fronds with softly rippled edges','one long broad bright-green fern frond with a dark central vein and gently rippled edge',false],
 ['elephant-ear','Elephant Ear','Alocasia macrorrhizos','broadleaf',1.4,1.4,'large upright heart-shaped green leaves with strong veins on fleshy stems','one large heart-shaped elephant-ear leaf, clear pale green branching veins, pointed tip',false],
 ['areca-palm','Areca Palm','Dypsis lutescens','palm-clump',1.4,1.8,'healthy clump of slender golden-green canes with arching feathered palm fronds','one arching feathered areca palm frond with narrow green leaflets on both sides of the rachis',true],
 ['dwarf-banana','Dwarf Banana','Musa acuminata','banana',1.9,2.2,'cluster of fleshy layered pseudostems and broad bright green paddle leaves with a few natural splits','one broad elongated banana leaf, central midrib, parallel veins and a few natural edge splits',false],
 ['pandan','Pandan','Pandanus amaryllifolius','rosette',1,.7,'dense spiralling rosette of narrow arching strap-shaped glossy green leaves','one long narrow pandan strap leaf, glossy medium green, tapered to a fine point',false],
 ['dwarf-plumeria','Dwarf Plumeria','Plumeria rubra','shrub',1.4,1.8,'thick smooth branching stems, terminal clusters of long oval leaves and a few white yellow-centred flowers','a terminal cluster of long oval green plumeria leaves with two white five-petal yellow-centred flowers',true],
 ['rain-tree','Rain Tree','Samanea saman','tree',23,16,'wide umbrella crown, spreading low branches, substantial textured trunk and dense fine compound foliage','a delicate rain-tree twig bearing several bipinnate green leaves with numerous tiny oval leaflets',false],
 ['banyan','Banyan','Ficus benghalensis','tree',18,14,'dense broad irregular crown, sturdy branching trunk with buttressed roots and a few aerial roots','a short branching ficus sprig carrying several thick glossy oval green leaves',false],
 ['tropical-almond','Tropical Almond','Terminalia catappa','tree',15,12,'distinct tiers of horizontal branches bearing large broad oval leaves, full healthy green canopy','a terminal cluster of broad obovate tropical almond leaves, rich green with visible lateral veins',false],
 ['mango-tree','Mango Tree','Mangifera indica','tree',11,10,'rounded dense crown and abundant drooping narrow glossy green leaves','a mango twig with a cluster of long narrow glossy green leaves, naturally drooping tips',false],
 ['tamarind','Tamarind','Tamarindus indica','tree',17,14,'irregular spreading crown, rugged trunk and fine pinnate green foliage','a tamarind twig bearing several pinnate leaves with many small paired oblong green leaflets',false],
 ['golden-shower','Golden Shower','Cassia fistula','tree',11,10,'rounded airy green canopy with a few cascading clusters of golden yellow flowers','a cassia twig with paired oval green leaflets and one restrained hanging yellow flower raceme',false],
 ['queens-crape-myrtle','Queen’s Crape Myrtle','Lagerstroemia speciosa','tree',11,12,'upright branching rounded crown, smooth mottled bark, green oval foliage and sparse lavender flower clusters','a twig bearing oval green leaves and a small cluster of lavender crepe-textured flowers',false],
 ['indian-mast-tree','Indian Mast Tree','Monoon longifolium','tree',4,14,'narrow tall columnar crown with drooping branches and long rippled deep green leaves','a hanging sprig of long narrow deep-green leaves with gently undulating margins',false],
 ['coconut-palm','Coconut Palm','Cocos nucifera','palm',10,16,'slightly curved ringed trunk, wide crown of arching feathered fronds, a few coconuts under the crown','one long coconut palm frond with many long thin green leaflets, gracefully drooping tip',false],
 ['foxtail-palm','Foxtail Palm','Wodyetia bifurcata','palm',7,12,'upright ringed trunk with green crownshaft and dense bottlebrush-like feathery fronds','one dense foxtail palm frond with abundant narrow green leaflets radiating around the rachis',false],
];
export const FOLIAGE = rows.map(([id,name,species,kind,width,height,form,leaf,potted],i)=>({id,name,species,kind,width,height,form,leaf,potted,tree:i>=10,seed:731+i*137}));
export const drafts = FOLIAGE.map(a=>({id:a.id,name:a.name,category:'vegetation',tags:['foliage','tropical','thai-street',a.tree?'tree':'plant','no-lightmap'],scale:{declared:{w:a.width,h:a.height,d:a.width}},pivot:'base-center',collider:'none',targetTriangles:a.tree?12000:2000,maxDrawCalls:a.tree?2:3,maxMaterials:a.tree?2:3,maxUniqueGeometries:a.tree?2:3,prompts:{image:`${a.species}: ${a.form}${a.potted?', in a simple weathered street planter':''}`,texture:'Natural leaf colour and venation, restrained colour variation, physically textured bark; no painted directional lighting on live-lit materials.'},notes:`Deterministic tropical foliage workflow: EZ-Tree branching geometry or Three.js botanical geometry. ${a.species}; ${a.form}. ${a.height} m authoring height. Not reconstructed with Meshy. No unique lightmap allocation. Mesh/detail/billboard variants share this catalogue entry. Containers and trunk collision are placement-specific; distant representations have no collision. Budget explicitly limits repeated vegetation despite its physical size.`}));
